baseURL = "https://martinc.me/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Martin Marquez Cervantes"
# Main Menu
[[menu.main]]
name = "Hola"
url = "#home"
weight = 1
[[menu.main]]
name = "Acerca"
url = "#about"
weight = 2
[[menu.main]]
name = "Comunidades"
url = "#service"
weight = 3
[[menu.main]]
name = "Proyectos"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "CV"
url = "#resume"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6
[[menu.main]]
name = "Contacto"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "Acerca de mí"
url = "#home"
weight = 1
[[menu.sitemap]]
name = "Ciencia"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "CodeMX"
url = "https://codemx.org"
weight = 4
[[menu.sitemap]]
name = "TecTec"
url = "https://tectecshop.com"
weight = 5

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © 2021"
footerLogo = "images/contact/widget-logom.png"
formspreeURL = "https://formspree.io/f/xaylgyeo"
googleAnalytics = "G-Q0GBJ2LZ1K"
logo = "images/site-navigation/logom.png"

[params.address]
address = "70 San Pedro de la Laguna, Zumpango de Ocampo, Edomex."
email = "martinmarcer@gmail.com"
openingHours = "Disponible de Lunes a Sabado"
phone = "+(52) 55 7174 8569"

[params.map]
APIkey = "AIzaSyB6FFTBF4paFNRCmr_eOMhzRXAou9MDuM8"
latitude = "19.776958"
longitude = "-99.116624"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/martin.marquezcervantes.5"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/martin-marquez-cervantes/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.instagram.com/martyeei/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/MarParkLP"
weight = 4
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/MarqCervMartin"
weight = 5
[[params.social]]
icon = "fa-youtube-square"
url = "https://www.youtube.com/channel/UCve0-mOyNxzTnr5HvHF0RSw/featured"
weight = 6
